mirigata_db:
  image: mysql:5.6
  ports:
    - ":3306"
  env_file:
    - passwords.env
  environment:
    MYSQL_DATABASE: mirigata_db
    MYSQL_USER: mirigata

mirigata:
  build: .
  links:
    - mirigata_db
  ports:
    - "80:8000"
  environment:
    DISCOVERY_MODE: env
    SECRET_KEY: hmza=$)j(tuainnvk415z*fwj^4#)*+!y20_n+yn1a$%=9yh=o

