database:
  image: mysql:5.6
  ports:
    - "13306:3306"
  env_file:
    - passwords.env
  environment:
    MYSQL_DATABASE: mirigata_db
    MYSQL_USER: mirigata

mirigata:
  build: .
  links:
    - database:mirigata_db
  ports:
    - "80:8000"
  env_file:
    - passwords.env

